### ISSUE TITLE
Ability to use custom parser?

### ISSUE THREAD

**Issue by grelas** [segmentio/dependency-report#9]
After installing and running `dependency-report` cli, I too was receiving the errors:
```
AST Runner failed on filepath: ./src/...
```
Most likely, this is due to the fact we're using ES6 decorators (i.e. `@withApollo`). When [upgrading](https://github.com/grelas/dependency-report/commit/482743161902d9416c7f9dcaac7c6836c25cfdb7) to `@babel/parser` instead of `babylon`, it was able to parse the `jsx` files without error. 

Maybe there could be an option to `DependencyReport` such as `parser` where one could leverage whatever parser/parser options they'd like?

**Comment by mshwery** [comment]
I've added this in #10
